local IPlayer = require("tic-tac-toe.player.IPlayer")
local Board = require("tic-tac-toe.board.Board")
local Mark = require("tic-tac-toe.board.Mark")

describe("IPlayer", function()
	it("throws when instantiated", function()
		expect(function()
			return IPlayer(Board(), Mark.X)
		end).to.throw()
	end)

	it("throws when trying to use getMove", function()
		local impl = IPlayer:extend()

		local obj = impl()
		expect(function()
			return obj:getMove()
		end).to.throw()
	end)
end)
